### ISSUE TITLE
Error installing electrs: failed to run custom build command for `librocksdb-sys v6.1.2`

### ISSUE THREAD

**Issue by rektlesspinko** [openoms/bitcoin-tutorials#10]
Got the following error running your electrs script. 

Compiling librocksdb-sys v6.1.2
error: failed to run custom build command for `librocksdb-sys v6.1.2`

Caused by:
  process didn't exit successfully: `/home/admin/electrs/target/release/build/librocksdb-sys-35c657b2df015019/build-script-build` (exit code: 101)
--- stdout
cargo:rerun-if-changed=build.rs
cargo:rerun-if-changed=rocksdb/
cargo:rerun-if-changed=snappy/
cargo:rerun-if-changed=lz4/
cargo:rerun-if-changed=zstd/
cargo:rerun-if-changed=zlib/
cargo:rerun-if-changed=bzip2/
cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
cargo:warning=set the LLVM_CONFIG_PATH environment variable to a valid `llvm-config` executable

--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:999:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

Any ideas?
Thanks

**Comment by openoms** [comment]
Please give details of what are you running on?
At least: 
Raspiblitz version or else
Hardware type (RPi3, RPi4, Odroid etc)

**Comment by rektlesspinko** [comment]
Hi,

RPi3b, Raspiblitz v1.2

This issue can be closed. I went back and manually ran each command in your shell script. For some reason, apt get resulted in a lot of network unreachable errors (presumably my internet connection?) so lots of dependencies were missing when it came to the the later install steps. Running each command in manually went through fine and now the DB is being built. 
Thanks
