### ISSUE TITLE
Electrs - Error: An unknown argument '--jsonrpc-import' was specified.

### ISSUE THREAD

**Issue by victorscones** [openoms/bitcoin-tutorials#11]
Trying to run:

`/home/admin/electrs/target/release/electrs --index-batch-size=10 --jsonrpc-import --db-dir /mnt/hdd/electrs/db --electrum-rpc-addr="0.0.0.0:50001" --cookie="raspibolt:PASSWORD_B" -vvvv`

and I'm receiving this error:

Error: An unknown argument '--jsonrpc-import' was specified.

Same issue with the `--cookie` argument as well.

**Comment by openoms** [comment]
Hi, not sure what the problem is, but certainly needs more context.
What hardware? Version of Raspiblitz?
Any other modification to the SDcard image?

Might be more productive to open an issue at https://github.com/romanz/electrs/issues.

**Comment by victorscones** [comment]
I'm running RaspiBlitz 1.3 on RP4. I'm trying to install Electrs from: https://github.com/openoms/bitcoin-tutorials/blob/master/electrs/README.md#electrum-server-in-rust-electrs-setup-on-the-raspiblitz

`cargo run --release -- -vvvv --index-batch-size=10 --jsonrpc-import --db-dir /mnt/hdd/electrs/db --cookie="raspibolt:$PASSWORD_B" --electrum-rpc-addr="0.0.0.0:50001"`

`/home/admin/electrs/target/release/electrs --index-batch-size=10 --jsonrpc-import --db-dir /mnt/hdd/electrs/db --electrum-rpc-addr="0.0.0.0:50001" --cookie="raspibolt:PASSWORD_B" -vvvv`

I replaced `--jsonrpc-import` with `--jsonrpc_import` and now that argument works, but `--cookie` is still giving me an unknown argument error. Was something changed recently?

**Comment by openoms** [comment]
I got the error too, lets see what the electrs team says.

**Comment by romanz** [comment]
First of all, sorry for the breakage!
This is probably a side effect from https://github.com/romanz/electrs/issues/151#issuecomment-528757361 - we meant to fix a security issue but didn't communicate well the reason behind it in the latest (unofficially) released version.

**Comment by romanz** [comment]
Will update on the https://github.com/romanz/electrs/issues/170.

**Comment by openoms** [comment]
The issue is fixed, just run the scripts again.

**Comment by victorscones** [comment]
Thanks, it's working now! Just waiting for it to build the database now.
