### ISSUE TITLE
Security issues

### ISSUE THREAD

**Issue by Kixunil** [openoms/bitcoin-tutorials#12]
I've [commented](https://github.com/openoms/bitcoin-tutorials/commit/175832bf59a3f32b764ce29cb81dd660590fc4b5) some security issues I've found. I don't consider them very serious but better have them patched. I opened this issue to track it.

**Comment by openoms** [comment]
Thanks, the script was due for some refactoring.
I have introduced a user `electrs`to run the service and made modifications to make the config file generation safer.

**Comment by Kixunil** [comment]
Looks good to me. There are some details I asked about, but nothing super-important.

**Comment by openoms** [comment]
Replied to the comments, useful suggestions, thank you!
