### ISSUE TITLE
Electrs: build fails with latest Rust version 1.38.0

### ISSUE THREAD

**Issue by openoms** [openoms/bitcoin-tutorials#18]

**Comment by openoms** [comment]
Rust 1.37.0 works
https://github.com/rust-lang/rustup.rs/blob/master/README.md#keeping-rustup-up-to-date

Check version Rust version with:
`/home/electrs/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/bin/rustc --version`

Need to keep Rust version 1.37 at until solved.

**Comment by richdbtc** [comment]
Downgrading to Rust 1.3.7 in the script results in build success for release target:

`sudo -u electrs /home/electrs/.cargo/bin/rustup install 1.37.0`
`sudo -u electrs /home/electrs/.cargo/bin/rustup override set 1.37.0`

**Comment by openoms** [comment]
> Downgrading to Rust 1.3.7 in the script results in build success for release target:
> 
> `sudo -u electrs /home/electrs/.cargo/bin/rustup install 1.37.0`
> `sudo -u electrs /home/electrs/.cargo/bin/rustup override set 1.37.0`

Thank you looking up the syntax, I have included it in the script until there is a solution.
Rust will be kept at the version v1.37.0 for now.

**Comment by grnqrtr** [comment]
Hey openoms, I just used your script yesterday `wget https://github.com/openoms/bitcoin-tutorials/raw/master/electrs/electrs_to_RaspiBlitz.sh && bash electrs_to_RaspiBlitz.sh` and build failed.

I then found this issue and checked my Rust version using `/home/electrs/.rustup/toolchains/stable-armv7-unknown-linux-gnueabihf/bin/rustc --version` which returns `rustc 1.38.0 (625451e37 2019-09-23)`. It seems like the script isn't keeping the version at v1.37.0 like it is supposed to.

**Comment by openoms** [comment]
@grnqrtr thansk for reporting. We need to find a way to keep rust 1.37 as the build on 1.38 is not solved do far on ARM: https://github.com/romanz/electrs/issues/174#issuecomment-542171448

**Comment by openoms** [comment]
@grnqrtr thanks for reporting. We need to find a way to keep rust 1.37 as the build on 1.38 is not solved so far on ARM: https://github.com/romanz/electrs/issues/174#issuecomment-542171448

**Comment by grnqrtr** [comment]
I ended up adding `--force` to your script at `sudo -u electrs /home/electrs/.cargo/bin/rustup install 1.37.0 --force` and re-running it, which seems to cause it to ignore that the components `'clippy'` and `'rustfmt'` are unavailable in 1.37.0. The script seemed to run and build fine, with no errors, though I'm not sure if this will cause problems with electrs since those components weren't included? I'm not a coder or anything, not really sure what I'm doing, but so far electrs seems to be running and starting to index. I'm also not sure why @richdbtc didn't need to include `--force`?

**Comment by openoms** [comment]
@grnqrtr thanks for the suggestion, I have updated the script to force Rust 1.37 for now. It is a hacky solution (first installs 1.38, then downgrades to 1.37) but works: https://github.com/openoms/bitcoin-tutorials/commit/4aa1ab954f5dcaa9409287a59ee3556a6cc973d2

**Comment by openoms** [comment]
Removed the workaround to keep on outdate Rust. Builds well on v1.39 on the RPi4. 
https://github.com/openoms/bitcoin-tutorials/commit/0f8714fd60174eebbabdcfbc95741ebf84f80c2d
