### ISSUE TITLE
Electrs Tor Port 50001 vs 50002

### ISSUE THREAD

**Issue by grnqrtr** [openoms/bitcoin-tutorials#20]
I'm sorry if I'm not documenting/creating this issue correctly, but I was having trouble connecting to my Electrs server over Tor but was able to eventually figure out a solution and think there might be an error in the documentation.

It seems like your script sets up the Tor Hidden Service with port 50002:
`        # Hidden Service for Electrum Server`
`        HiddenServiceDir /mnt/hdd/tor/electrs`
`        HiddenServiceVersion 3`
`        HiddenServicePort 50002 127.0.0.1:50002`

But these directions (https://github.com/openoms/bitcoin-tutorials/tree/master/electrs) tell you to connect over 50001:
`electrum --oneserver --server Tor_address.onion:50001:t --proxy socks5:127.0.0.1:9150`

I ended up changing how the script setup the Tor Hidden Service from 50002 to 50001 and now things are working fine.

**Comment by openoms** [comment]
Did you try connecting via:
 `electrum --oneserver --server Tor_address.onion:50002:s --proxy socks5:127.0.0.1:9150`

This would use SSL through Tor. We can add 50001 and 50002 to the torrc as well.
I have changed it in the script to 50002 because Electrum on mobile would only take the SSL connection.
Will update the docs, thanks!

**Comment by openoms** [comment]
Updated the Tor guide to clarify this: https://github.com/openoms/bitcoin-tutorials/commit/a5240cabeae9bf0adc51a00e4ac966c791cbff12

**Comment by grnqrtr** [comment]
> Did you try connecting via:
> `electrum --oneserver --server Tor_address.onion:50002:s --proxy socks5:127.0.0.1:9150`

I must not have tried that, but just did and works. I set torrc back to 50002. Thank you!
