### ISSUE TITLE
JoinMarket - Upgrading

### ISSUE THREAD

**Issue by victorscones** [openoms/bitcoin-tutorials#23]
How would I go about upgrading JoinMarket to 0.6.1? I currently have JoinMarket 0.5.5 running on my RaspiBlitz. Is it safe to follow the 'Installation' instructions for performing an upgrade to JoinMarket?

**Comment by openoms** [comment]
Follow the joinmarket docs: 
https://github.com/JoinMarket-Org/joinmarket-clientserver/blob/master/docs/release-notes/release-notes-0.6.1.md#upgrading

In our case:

```
cd joinmarket-clientserver
git pull
git reset --hard v0.6.1
./install.sh
```

**Comment by openoms** [comment]
Tested, updating to v0.6.1 works with the above method.
