### ISSUE TITLE
 LND Connect Error while make install ( Makefile:4: recipe for target 'dep' failed)

### ISSUE THREAD

**Issue by ElSpiestolero** [openoms/bitcoin-tutorials#3]
Following the tutorial to get Raspiblitz connected to ZeusLN i get the following error.
First there was no Go installed so i did that using: 

https://gist.github.com/simoncos/49463a8b781d63b5fb8a3b666e566bb5

And now after the command: make install 

i get the error:
 /usr/local/go/src/runtime/internal/sys/arch_wasm.go:8:24: too many errors
Makefile:4: recipe for target 'dep' failed
make: *** [dep] Error 2

What could be the reason? 

![Knipsel Bitcoin Node Onion](https://user-images.githubusercontent.com/48837598/55289882-6e459b00-53cc-11e9-9886-e3a446e47f65.JPG)

**Comment by openoms** [comment]
Hi! 
Which version of RaspiBlitz are you on? (latest is 1.1 and that is what I was testing).
Go must have been installed before since LND needs it, so that is strange.

**Comment by openoms** [comment]
My output running the guide on a fresh 1.1 RaspiBlitz image:
```
admin@RaspiBlitz:~ $ go get -d github.com/LN-Zap/lndconnect
admin@RaspiBlitz:~ $ cd ~/go/src/github.com/LN-Zap/lndconnect
admin@RaspiBlitz:~/go/src/github.com/LN-Zap/lndconnect $ make install
go get ./...
go install -v ./...
admin@RaspiBlitz:~/go/src/github.com/LN-Zap/lndconnect $ cd ~/go/bin
admin@RaspiBlitz:~/go/bin $ ./lndconnect ...
```
There must be something wrong your setup.
Double check that you are logged in to the right place. Is your RaspiBlitz`s hostname Bitcointiel?I Recommend to update your RaspiBlitz to the latest:
https://github.com/rootzoll/raspiblitz/#updating-to-new-version

**Comment by ElSpiestolero** [comment]
Thanks for your response. I am getting:

admin@bitcointiel:~ $ go version
-bash: go: command not found

Your first command gives me this error:
admin@bitcointiel:~ $ wget https://storage.googleapis.com/golang/go${goVersion}.linux-armv6l.tar.gz
--2019-03-31 21:25:57--  https://storage.googleapis.com/golang/go.linux-armv6l.tar.gz
Resolving storage.googleapis.com (storage.googleapis.com)... 172.217.19.208, 2a00:1450:400e:80b::2010
Connecting to storage.googleapis.com (storage.googleapis.com)|172.217.19.208|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2019-03-31 21:25:58 ERROR 404: Not Found.

My hostname is indeed Bitcointiel. My LND won't start unless i use the command:  ./70initLND.sh . Could this be the same issue with Go?  https://github.com/rootzoll/raspiblitz/issues/450

**Comment by openoms** [comment]
>Your first command gives me this error:
sorry, that was my fault, updated now: 
`wget https://storage.googleapis.com/golang/go1.11.linux-armv6l.tar.gz`

>My LND won't start unless i use the command: ./70initLND.sh . 

If this is still an issue after you have fully set up your Raspiblitz, than I would recommend to start new with a fresh SDcard image. (the blockchain is on the HDD, that won`t need to be synced again)

Also this guide is meant for a working RaspiBlitz v1.1 with Tor installed.

**Comment by ElSpiestolero** [comment]
Did a fresh download and install of Raspiblitz 1.1. This fixed the LND problem. Just having some trouble with the commands now. Go is not running yet.

![Knipsel Bitcoin Node Onion](https://user-images.githubusercontent.com/48837598/55359780-f8782700-54d2-11e9-9f92-eda03756fe38.JPG)

**Comment by openoms** [comment]
Did you just download the 1.1 SD card image or did you build it yourself (from the raspbian image)?

Can you tell at which point did you change the hostname of your RaspiBlitz to Bitcointiel?
During the SDcard building process a non-default hostname will mess up the setup.

**Comment by ElSpiestolero** [comment]
I downloaded the 1.1 SD card image from the server pre made. 

I changed the hostname once to bitcointiel when using the /70initLND.sh and now i input that name when i installed again.

**Comment by openoms** [comment]
Added more commands to the go installation, including adding to the PATH and GOPATH:
```
$ wget https://storage.googleapis.com/golang/go1.11.linux-armv6l.tar.gz
$ sudo tar -C /usr/local -xzf go1.11.linux-armv6l.tar.gz
$ sudo rm *.gz
$ sudo mkdir /usr/local/gocode
$ sudo chmod 777 /usr/local/gocode
$ export GOROOT=/usr/local/go
$ export PATH=$PATH:$GOROOT/bin
$ export GOPATH=/usr/local/gocodea
$ export PATH=$PATH:$GOPATH/bin
```

**Comment by ElSpiestolero** [comment]
Thanks for your patience in helping me out. Looks like now i am getting somewhere. Just got an error when using go get -d github.com/LN-Zap/lndconnect 
![Knipsel Bitcoin Node Onion](https://user-images.githubusercontent.com/48837598/55430195-c24bad80-558d-11e9-9238-4c72533bf8d8.JPG)

**Comment by openoms** [comment]
ahh, there has been a typo on this (now corrected). Run the without the `a` on the end:
`export GOPATH=/usr/local/gocode` and retry :face_with_head_bandage:

**Comment by ElSpiestolero** [comment]
Still couldn't run Go on my raspiblitz. Tried the command:

export PATH=$PATH:/usr/local/go/bin # put into ~/.profile

From webpage: https://tutorials.technology/tutorials/Install-Golang-1_10-on-Raspberry-Pi.html
And that seems to fix it. Have no idea why :)

**Comment by openoms** [comment]
Sorry i might not have been clear enough. You need to run these commands after each other and that includes adding the required paths:

> Added more commands to the go installation, including adding to the PATH and GOPATH:
> 
> $ wget https://storage.googleapis.com/golang/go1.11.linux-armv6l.tar.gz
> $ sudo tar -C /usr/local -xzf go1.11.linux-armv6l.tar.gz
> $ sudo rm *.gz
> $ sudo mkdir /usr/local/gocode
> $ sudo chmod 777 /usr/local/gocode
> $ export GOROOT=/usr/local/go
> $ export PATH=$PATH:$GOROOT/bin
> $ export GOPATH=/usr/local/gocode
> $ export PATH=$PATH:$GOPATH/bin

These two lines:
> $ export GOROOT=/usr/local/go
> $ export PATH=$PATH:$GOROOT/bin

do the same as this: 
>export PATH=$PATH:/usr/local/go/bin

I will work on to have this all automated, so you will only need to use the menu on the RaspiBlitz,
Thank you for testing in the meantime! 
So do you have your Zeus wallet connected yet?

**Comment by ElSpiestolero** [comment]
I did run the commands after each other but only after "export PATH=$PATH:/usr/local/go/bin # put into ~/.profile"  command did it work. And then i did have a go version. 

 Yes now running Zeus wallet :)

**Comment by openoms** [comment]
Well done and thanks for the feedback! Closing this now, but let me know about any other problem.
