### ISSUE TITLE
Slight suggestions

### ISSUE THREAD

**Issue by woeisme** [openoms/bitcoin-tutorials#32]
It would be useful to add instructions on copy / pasting the host / macaroon data via text to the Zap / Zeus tutorials with pictures. 

The FOSS tool scrcpy might be useful for some people to copy / paste long strings of text to the phone for setup.

**Comment by openoms** [comment]
I think connecting to the node via ssh with Termux or Termius directly from the phone is more simple. At least that is what I'd do. Not familiar with the tool you mentioned.
