### ISSUE TITLE
Can't connect Blitz to Zap or Zeus via QR.

### ISSUE THREAD

**Issue by MrShparkle** [openoms/bitcoin-tutorials#36]
Pi is on and Synced. Haven't managed to get any wallet apps to reference it as far as I know aside from the Browser GUIs for RTL and Specter. Can't manage to get standalone Specter Desktop to connect, nor Electrum. Wasabi always says "Backend is Connected" regardless of what IP I add in the Config so I assume that is not looking at the Blitz either.

When I scan the "Android Zeus" or "Android Zap" QRs with respective wallets, nothing happens. Like there's no QR in front of the scanner. Managed to shrink QR on pc screen but still no response.

Trying it all again with TOR active now so I'll see if that helps anything.

Could it be that the Pi has ethernet cable but Windows PC is on network via wifi?

**Comment by openoms** [comment]
You need to make sure that the phone and the RPi are on the same network and can test QRs with a simple QRcode scanner.
Should shown the same string which you get using the command `lndconnect -j`.

Please refer to https://github.com/rootzoll/raspiblitz/issues and join t.me/raspiblitz for general questions.

Closing as not relevant to this repo.
