### ISSUE TITLE
Add Joinmarket Qt desktop icon

### ISSUE THREAD

**Issue by clay-v** [openoms/bitcoin-tutorials#40]
I was following @k3tan172 's [tutorial for Joinmarket](https://www.youtube.com/watch?v=zTCC86IUzWo) in relation to the [Fastest way to coinjoin](https://github.com/clay-v/joinMarketDocs/projects/1) and he points to https://github.com/openoms/bitcoin-tutorials/pull/24, where he details how to add the icon. The PR was merged but then undone by https://github.com/openoms/bitcoin-tutorials/pull/26.

**Comment by openoms** [comment]
thanks for reporting, but the instructions to use an icon is added back to here: https://github.com/openoms/bitcoin-tutorials/blob/master/joinmarket/joinmarket_desktop_to_blitz.md#joinmarket-qt-iconshortcut-on-the-linux-desktop
