### ISSUE TITLE
Dead link LND updates

### ISSUE THREAD

**Issue by NilByte** [openoms/bitcoin-tutorials#42]
On:
https://github.com/openoms/bitcoin-tutorials/tree/master/raspiblitz.updates

Link not working:
https://github.com/openoms/lightning-node-management/blob/master/lnd.updates/README.md

Working:
https://github.com/openoms/lightning-node-management/blob/master/technicals/lnd.updates.md

**Comment by openoms** [comment]
thanks for reporting
