### ISSUE TITLE
Dead link JoinMarket orderbook update

### ISSUE THREAD

**Issue by bitpaint** [openoms/bitcoin-tutorials#43]
Hey, in  [README.md](https://github.com/openoms/bitcoin-tutorials/blob/27bdc363a3e93ce926891c2b1f7273c791437feb/joinmarket/README.md)
`https://joinmarket.me/ob/` is a dead link. You can replace it with `https://nixbitcoin.org/obwatcher/`

**Comment by openoms** [comment]
thanks for reporting!
