### ISSUE TITLE
had trouble with raspiblitz setup for electrs

### ISSUE THREAD

**Issue by My-daughters-keeper** [openoms/bitcoin-tutorials#53]
hey guys
i used your guide to try and setup electrs with my raspiblitz node.

i managed to run the 304 lines of script
and before i could run the install rust etc command my node has stopped connecting .
no peers, lightning wallet keeps asking for password over and over and electrum not running.

the raspiblitz screen says check sudo journalctl -u electrs

i kept getting bash command not found. i had to change the $ for sudo in the $ wget script and then it loaded the script but still no connection to peers or electrs

i got into the raspiblitz menu and loged into the lnd wallet through command prompt so i can see the raspiblitz screen.

if i got to electrs in the menu it says electrs not running and gives me some debug info. which im unsure hot to copy to show anyone! lol

can i undo everything i did and start again?
sounds like a shambles. but any help would be appreciated 
cheers

**Comment by openoms** [comment]
Electrs install is automated on the Raspiblitz, use the SERVICE menu.
 
To start clean reflash the SDcard with the latest Raspiblitz image.
